<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Hale_MRI</RootNamespace>
    <StartupObject>Sub Main</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
    <MyType>WindowsForms</MyType>
    <Platforms>AnyCPU;x64</Platforms>
    <Configurations>Debug;Release;NoEncoders</Configurations>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineTrace>False</DefineTrace>
    <Optimize>True</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DefineTrace>False</DefineTrace>
    <Optimize>True</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <Optimize>False</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='NoEncoders|AnyCPU'">
    <DefineConstants>$(DefineConstants)NO_ENCODERS,DEBUG</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='NoEncoders|x64'">
    <DefineConstants>$(DefineConstants)NO_ENCODERS,DEBUG</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Old Stuff\**" />
    <EmbeddedResource Remove="Old Stuff\**" />
    <None Remove="Old Stuff\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="ChartAngularPosition.Designer.vb" />
    <Compile Remove="ChartAngularPosition.vb" />
    <Compile Remove="ChartBladeHeight.Designer.vb" />
    <Compile Remove="ChartBladeHeight.vb" />
    <Compile Remove="DisplayControl.Designer.vb" />
    <Compile Remove="DisplayControl.vb" />
    <Compile Remove="Form3.Designer.vb" />
    <Compile Remove="Form3.vb" />
    <Compile Remove="Form4.Designer.vb" />
    <Compile Remove="Form4.vb" />
    <Compile Remove="FrmJobs_old.Designer.vb" />
    <Compile Remove="FrmJobs_old.vb" />
    <Compile Remove="newFrmJobs.Designer.vb" />
    <Compile Remove="newFrmJobs.vb" />
    <Compile Remove="ReportHeader.Designer.vb" />
    <Compile Remove="ReportHeader.vb" />
    <Compile Remove="ReportLetterhead.Designer.vb" />
    <Compile Remove="ReportLetterhead.vb" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="ChartAngularPosition.resx" />
    <EmbeddedResource Remove="ChartBladeHeight.resx" />
    <EmbeddedResource Remove="DisplayControl.resx" />
    <EmbeddedResource Remove="Form3.resx" />
    <EmbeddedResource Remove="Form4.resx" />
    <EmbeddedResource Remove="FrmJobs_old.resx" />
    <EmbeddedResource Remove="FrmReportsEditor.resx" />
    <EmbeddedResource Remove="newFrmJobs.resx" />
    <EmbeddedResource Remove="ReportHeader.resx" />
    <EmbeddedResource Remove="ReportLetterhead.resx" />
  </ItemGroup>

  <!--<ItemGroup>
    <Compile Remove="FrmJobs.Designer.vb" />
    <Compile Remove="FrmJobs.vb" />
    <Compile Remove="FrmJobs_old.Designer.vb" />
    <Compile Remove="FrmJobs_old.vb" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="FrmJobs.resx" />
    <EmbeddedResource Remove="FrmJobs_old.resx" />
  </ItemGroup>-->

  <ItemGroup>
    <Import Include="System.Data" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EntityFrameworkCore.Jet" Version="8.0.0" />
    <PackageReference Include="EntityFrameworkCore.Jet.Data" Version="8.0.0" />
    <PackageReference Include="EntityFrameworkCore.Jet.Odbc" Version="8.0.0" />
    <PackageReference Include="EntityFrameworkCore.Jet.OleDb" Version="8.0.0" />
    <PackageReference Include="EntityFrameworkCore.VisualBasic" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Data.Odbc" Version="8.0.1" />
    <PackageReference Include="System.Data.OleDb" Version="8.0.1" />
    <PackageReference Include="WinForms.DataVisualization" Version="1.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibDatabase\LibDatabase.vbproj" />
    <ProjectReference Include="..\LibDisplayControls\LibDisplayControls.vbproj" />
    <ProjectReference Include="..\LibEncoder\LibEncoder.vbproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="My Project\Application.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
    </Compile>
    <Compile Update="My Project\Resources.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="My Project\Resources.resx">
      <CustomToolNamespace>My.Resources</CustomToolNamespace>
      <Generator>VbMyResourcesResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.vb</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
  </ItemGroup>

  <Import Project="..\CommonSettings.targets" />

</Project>