<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>LibEncoder</RootNamespace>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
    <ImportedNamespaces>USB4Wrapper=False,Microsoft.VisualBasic=True,System=True,System.Collections=True,System.Collections.Generic=True,System.Diagnostics=True,System.Linq=True,System.Xml.Linq=True,System.Threading.Tasks=True,LibEncoder=True</ImportedNamespaces>
    <Configurations>Debug;Release;NoEncoders</Configurations>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>True</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <Optimize>True</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
    <DefineDebug>True</DefineDebug>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <Optimize>False</Optimize>
    <DefineDebug>True</DefineDebug>
  </PropertyGroup>

  <ItemGroup Condition="'$(Configuration)' == 'NoEncoders'">
	<Compile Remove="USDigital.vb" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' != 'NoEncoders'">
	<Compile Remove="USB4_No_Encoders.vb" />
	<Compile Remove="USDigital_No_Encoders.vb" />
    <Reference Include="USB4Wrapper">
      <HintPath>..\..\..\..\..\..\..\Program Files (x86)\US Digital\USB4\Common\USB4Wrapper.dll</HintPath>
    </Reference>
    <Import Include="USB4Wrapper" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <None Update="USB4.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
